### PR TITLE
Merge pull request #1 from afawcett/master

### PR DESCRIPTION
**Pull request by matcadg**
Update

### CODE REVIEW

**Comment by matcadg** [comment]
update

**Comment by afawcett** [comment]
Hi @matcadg i'm finding it hard to know what your proposing here can you explain?

**Comment by matcadg** [comment]
Hi Andrew,

my mistake, not proposing anything, wrong base and update direction :/ ,
was trying to update my fork.

Thanks for the great tool,

take care
Matt

2015-09-26 6:02 GMT+02:00 Andrew Fawcett <notifications@github.com>:

> Hi @matcadg <https://github.com/matcadg> i'm finding it hard to know what
> your proposing here can you explain?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/afawcett/declarative-lookup-rollup-summaries/pull/249#issuecomment-143396137>
> .
>



-- 



*Pozdrawiam,Mateusz Gutowskitel. 505 531 292*
facebook.com/CareFinance <https://www.facebook.com/CareFinance>

**Comment by afawcett** [comment]
Ah ok, no worries, and thanks! :+1:

**Pull request closed without merging**
