### PR TITLE
Issue214 activation without trigger

### PR DESCRIPTION
**Pull request by jondavis9898**
Add global setting to support bypassing of trigger exists check during rollup summary activation.

Additional capabilities could be added to specify regex or "pattern" to enforce in addition to or instead of the bypass.  Given the possible combinations of naming conventions individual use, a simple bypass flag was added.  By default, triggers are still required to support activation.

### CODE REVIEW

**Comment by afawcett** [comment]
Thanks for this, though this validation can be disabled by using Developer mode, that was the original intent for your use case here. Though it seems folks do want to full emulate what the triggerHandler does. So what is missing is in the API a means to do the work triggerHandler does basically (which although public was not really intended to be an API). So something like an override for dlrs.RollupService.rollup, e.g. dlrs.RollupService(Map<ID, SObject> oldRecords, Map <ID, SObject> newRecords). This new API entry method would look for Developer mode DLRS records (like the current API entry method). Make sense?

**Comment by afawcett** [comment]
Take a look at the discussion on this issue for a bit more background, https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/165.

**Comment by jondavis9898** [comment]
#165 showed me the light and clued me in to what I think you are thinking.  Updated my comments in #208 with a summary.  If my understanding is correct, I think exposing an API to mimick triggerHandler would meet my need and be a much better approach than what I proposed.

**Comment by jondavis9898** [comment]
I think this can be closed as we've shifted to approach in PR #208

**Pull request closed without merging**
